[build]
    command = "pip install -r requirements.txt && uvicorn main:app --host 0.0.0.0 --port $PORT"
    publish = "path_to_your_public_folder"

[dev]
    command = "uvicorn main:app --reload --port 8000"

[[redirects]]
    from = "/api/*"
    to = "http://localhost:8000/:splat"
    status = 200