[build]
    command = "pip install -r requirements.txt && uvicorn main:app --reload --port 8000"

[dev]
    command = "uvicorn main:app --reload --port 8000"

[[redirects]]
    from = "/api/*"
    to = "http://localhost:8000/:splat"
    status = 200